# syntax=docker/dockerfile:1
FROM maven:3.6.1-jdk-8 as build

WORKDIR /usr/src/app

COPY pom.xml .
COPY src src
RUN mvn install

FROM jboss/wildfly:8.2.1.Final as runtime
WORKDIR /opt/jboss/wildfly/bin/

COPY --from=build /usr/src/app/target/IntegracoesH4P.war /opt/jboss/wildfly/standalone/deployments/IntegracoesH4P.war

CMD ["standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]